# See https://prettier.io/docs/en/options.html
arrowParens: 'avoid'
printWidth: 120
singleQuote: true
trailingComma: es5
overrides:
  - files:
      - '**/*.handlebars'
      - '**/*.hbs'
    options:
      singleQuote: false
  - files: '*.css'
    options:
      singleQuote: false
  - files:
      - '.ember-cli'
      - '.watchmanconfig'
      - '*.code-workspace'
    options:
      parser: 'json'
